image: openjdk:11-jdk

stages:
  - build
  - publish
  - deploy

before_script:
  - echo $GRADLE_HOME
  - echo `pwd`
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/
  - chmod +x gradlew
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:gradle:
  stage: build
  only:
    - tags
  script:
    - ./gradlew buildAndReport
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - ./build/reports/tests/
      - ./build/reports/checkstyle/
      - ./build/jacocoHtml
    expire_in: 1 week


pages:

  stage: publish


  script:
    - pwd
    - mv ./build/reports/tests/ public
    - mv ./build/reports/checkstyle/ public
    - mv ./build/jacocoHtml/ public
    - pwd
    - ls -lR public

  artifacts:
    paths:
      - public

  only:
    - tags